@api = http://localhost:3000/api

GET {{api}}/requestsglobal/1

###
GET {{api}}/1

###

GET {{api}}/count

###

POST {{api}}/register
Content-Type: application/json

{
  "title": "Fifth post",
  "description": "Description of test post"
}

###

DELETE {{api}}/6

###

PUT {{api}}/5
Content-Type: application/json

{
  "title": "Fourth post",
  "description": "Description of test post"
}